name: professional_contact
description: "Share your professional contact easily with a QR Code."
publish_to: "none"
version: 1.0.1+5
homepage: https://github.com/hotaydev/professional-contact-app
repository: https://github.com/hotaydev/professional-contact-app.git
issue_tracker: https://github.com/hotaydev/professional-contact-app/issues
license: AGPL-3.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  device_info_plus: ^11.1.1
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  http: ^1.2.2
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/logo-dark.png
    - assets/images/logo-light.png
    - assets/images/social/github.png
    - assets/images/social/gravatar.png
    - assets/images/social/mastodon.png

  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
