name: professional_contact
description: "Share your professional contact easily with NFC and QR Code."
publish_to: "none"
version: 1.0.0+1
homepage: https://github.com/hotaydev/professional-contact-nfc
repository: https://github.com/hotaydev/professional-contact-nfc.git
issue_tracker: https://github.com/hotaydev/professional-contact-nfc/issues

environment:
  sdk: ^3.5.3

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  nfc_manager: ^3.5.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pretty_qr_code: ^3.3.0
  provider: ^6.1.2
  share_plus: ^10.0.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icon/hotay-logo/
